server:
  port: 8081

spring:
  h2:
    console:
      enabled: false

application:
  local:
    datasource:
      url: jdbc:h2:mem:mydb
#      url: jdbc:h2:tcp://localhost:9092/mem:mydb
      username: sa
      password: password
      driverClassName: org.h2.Driver
  postgres:
    datasource:
      url: jdbc:postgresql://host.docker.internal:5432/vocabulary
      username: artem
      password:
#      url: jdbc:postgresql://localhost:5432/vocabulary
#      username: vocabulary
#      password: vocabulary
      driverClassName: org.postgresql.Driver
  hibernate:
    hbm2ddlAuto: none
    showSql: true
    formatSql: true

liquibase:
  enable: true