#server:
#  port: 8080


#spring:
#  datasource:
#    password:
#    username:
#    url:
#    driver-class-name:

spring:
  h2:
    console:
      enabled: false

application:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  hibernate:
    hbm2ddlAuto: none
    showSql: true